### ISSUE TITLE
Standard Camera module support?

### ISSUE THREAD

**Issue by Aathish04** [automaticdai/rpi-object-detection#1]
Does this Program work with the raspberry pi's standard camera module?

**Comment by automaticdai** [comment]
Hi, I didn't test with the official camera module. 
My guess is it may not work because the driver is quite different. 

Any way I will give a try, and I will let you know the result.

**Comment by Aathish04** [comment]
Hello,

Thank You for the speedy response, I really appreciate it!

Thanking You.

**Comment by automaticdai** [comment]
Hi, it seems like you can't use standard operations of OpenCV. Instead, you have to use 'picamera' module, and can access camera with the following example code:

`
# import the necessary packages
from picamera.array import PiRGBArray
from picamera import PiCamera
import time
import cv2
 
# initialize the camera and grab a reference to the raw camera capture
camera = PiCamera()
rawCapture = PiRGBArray(camera)
 
# allow the camera to warmup
time.sleep(0.1)
 
# grab an image from the camera
camera.capture(rawCapture, format="bgr")
image = rawCapture.array
 
# display the image on screen and wait for a keypress
cv2.imshow("Image", image)
cv2.waitKey(0)
`

**Comment by Aathish04** [comment]
Thank you so much!
I will try the same.
