### ISSUE TITLE
Show fps in the window

### ISSUE THREAD

**Issue by automaticdai** [automaticdai/rpi-object-detection#4]

**Comment by pitfisher** [comment]
Hello! I implemented function to draw FPS count in OpenCV image window. It can be seen [here ](https://github.com/pitfisher/rpi-object-detection/tree/fps_visualization). Though I'v made a mistake and based that branch on my previous commit that is not in your repository so it can't be PR'd as is. But is the function all right?

**Comment by automaticdai** [comment]
Hi, the function does look okay to me. Please go ahead and submit a pull request and I will check from there.
