### ISSUE TITLE
PR with requirements.txt

### ISSUE THREAD

**Issue by pitfisher** [automaticdai/rpi-object-detection#9]
Hello! It's pretty usual for Python projects to have a list of dependencies in requirements.txt file. I launched all of your examples and figured out that installing module opencv-python with pip is sufficient to use all of them, but still it would be more convenient to have that kind of file. Will you accept my PR with that file?

**Comment by automaticdai** [comment]
That sounds good. Please go ahead and submit a PR. Thanks,
